### ISSUE TITLE
Icon Issue.

### ISSUE THREAD

**Issue by boredofnames** [Genteki/pyvts#39]
Icon doesn't seem to work. If I understood correctly:

[Here](https://github.com/Genteki/pyvts/blob/main/pyvts/vts.py#L58), you're setting self.plugin_icon as what's passed to plugin_info, and setting self.icon to None.

Then, you're referencing self.icon, instead of self.plugin_icon [here](https://github.com/Genteki/pyvts/blob/main/pyvts/vts_request.py#L85), which will always be None.

Thanks for working on this lib, I appreciate the time saved.

**Comment by Genteki** [comment]
Right, I forgot it.

I would try to fix.
